/** Mực Đỏ Thực Hành: Phiếu thi thử có timer, không dùng câu hỏi hư cấu ngoài dữ liệu lesson. */
import { AudioCoach } from "@/components/AudioCoach";
import { getLessonById } from "@/data/courseData";
import { mockTests, type MockTestConfig, type MockTestItem } from "@/data/mockTests";
import { normalizeChinese, scoreMultipleChoice } from "@/lib/assessment";
import type { ExerciseResult, SkillId } from "@/lib/types";
import { ChevronLeft, ChevronRight, Clock3, Play, Trophy } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

function formatSeconds(seconds: number) { return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export function MockTestWorkspace({ onRecord, onPractice }: { onRecord: (result: Omit<ExerciseResult, "attemptedAt">) => void; onPractice: (lessonId: string, skill: SkillId) => void }) {
  const [selectedId, setSelectedId] = useState(mockTests[0].id);
  const config = useMemo(() => mockTests.find((test) => test.id === selectedId) ?? mockTests[0], [selectedId]);
  const [active, setActive] = useState<MockTestConfig | null>(null);
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [remaining, setRemaining] = useState(config.durationSeconds);
  const [running, setRunning] = useState(false);
  const [score, setScore] = useState<number | null>(null);
  useEffect(() => { if (!active || !running || remaining <= 0) return; const timer = window.setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [active, running, remaining]);
  useEffect(() => { if (remaining === 0) setRunning(false); }, [remaining]);
  const begin = () => { setActive(config); setIndex(0); setAnswers({}); setScore(null); setRemaining(config.durationSeconds); setRunning(true); };
  if (!active) return <div className="page-content generic-page"><div className="section-kicker"><span>THI THỬ</span><b>NGHE · ĐỌC · VIẾT</b></div><div className="page-heading"><div><h1>Phiếu kiểm tra theo mốc</h1><p>Chọn mức phù hợp. Phần nói là bài luyện bổ sung và không được gắn nhãn là phần thi HSK3 tiêu chuẩn.</p></div></div><div className="mock-test-picker">{mockTests.map((test) => <button key={test.id} className={test.id === selectedId ? "is-selected" : ""} onClick={() => setSelectedId(test.id)}><span>{test.questions.length} câu · {formatSeconds(test.durationSeconds)}</span><b>{test.label}</b><p>{test.description}</p></button>)}</div><button className="primary-action" onClick={begin}><Play size={17} fill="currentColor" /> Bắt đầu {config.label}<ChevronRight size={18} /></button></div>;
  const item = active.questions[index]; const lesson = getLessonById(item.lessonId); const answer = answers[item.id] ?? "";
  const updateAnswer = (value: string) => setAnswers((current) => ({ ...current, [item.id]: value }));
  const submit = () => { const results = active.questions.map((question) => { const given = answers[question.id] ?? ""; const itemScore = question.skill === "writing" ? Number(normalizeChinese(given) === normalizeChinese(question.correctAnswer)) * 100 : scoreMultipleChoice(given, question.correctAnswer); onRecord({ exerciseId: question.id, lessonId: question.lessonId, skill: question.skill, answer: given, correctAnswer: question.correctAnswer, score: itemScore, explanation: question.explanation, questionType: "mock-test" }); return itemScore; }); setScore(Math.round(results.reduce((sum, value) => sum + value, 0) / results.length)); setRunning(false); };
  if (score !== null) return <div className="page-content generic-page"><div className="section-kicker"><span>THI THỬ</span><b>KẾT QUẢ & BƯỚC ÔN LẠI</b></div><div className="page-heading"><div><h1>{active.label}</h1><p>Điểm dưới đây là kết quả phiếu luyện; hãy dùng danh sách lỗi để quay lại đúng lesson.</p></div><div className="overview-stat"><b>{score}</b><span>/100</span></div></div><section className="mock-summary mock-result"><Trophy size={28} /><h3>Đã lưu {active.questions.length} câu trả lời</h3><p>Các câu chưa đúng đã được đưa vào mục Ôn tập cùng lời giải và liên kết lesson tương ứng.</p><button onClick={() => onPractice(active.questions.find((question) => (answers[question.id] ?? "") !== question.correctAnswer)?.lessonId ?? active.questions[0].lessonId, "listening")}>Ôn lỗi đầu tiên <ChevronRight size={15} /></button><button onClick={() => setActive(null)}>Chọn đề khác</button></section></div>;
  return <div className="page-content generic-page"><div className="section-kicker"><span>THI THỬ</span><b>PHIẾU LÀM BÀI · {index + 1}/{active.questions.length}</b></div><div className="page-heading"><div><h1>{active.label}</h1><p>{active.description}</p></div><div className="test-time"><Clock3 size={16} /><b>{formatSeconds(remaining)}</b><button onClick={() => setRunning((value) => !value)}>{running ? "Tạm dừng" : "Tiếp tục"}</button></div></div><div className="mock-layout"><section className="mock-sheet"><div className="mock-section-title"><span>{item.skill === "listening" ? "NGHE" : item.skill === "reading" ? "ĐỌC" : "VIẾT"}</span><h3>Câu {index + 1}</h3></div>{item.skill === "listening" && lesson && <AudioCoach chinese={lesson.listening.transcript} pinyin={lesson.listening.pinyin} translation={lesson.listening.translation} audioSrc={lesson.listening.audioSrc} />}{item.skill === "reading" && lesson && <p className="mock-passage" lang="zh-CN">{lesson.reading.passage}</p>}<p>{item.prompt}</p>{item.question ? <div className="mock-options">{item.question.options.map((option) => <label key={option.id}><input type="radio" name={item.id} value={option.id} checked={answer === option.id} onChange={(event) => updateAnswer(event.target.value)} /> {option.label}</label>)}</div> : <input value={answer} onChange={(event) => updateAnswer(event.target.value)} placeholder="Nhập câu tiếng Hoa" lang="zh-CN" />}</section><aside className="mock-summary"><p><b>Ba phần của phiếu</b></p><p>{active.listeningCount} nghe · {active.readingCount} đọc · {active.writingCount} viết</p><p className="muted">Bài nói được luyện riêng trong lesson, không phải phần thi HSK3 tiêu chuẩn.</p><button onClick={() => setIndex((current) => Math.max(0, current - 1))} disabled={index === 0}><ChevronLeft size={15} /> Câu trước</button>{index < active.questions.length - 1 ? <button onClick={() => setIndex((current) => current + 1)}>Câu sau <ChevronRight size={15} /></button> : <button className="primary-action primary-action--compact" onClick={submit}>Nộp bài</button>}</aside></div></div>;
}
